buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
    }
}

apply plugin:'base'


task npmInstall(type:Exec) {
    description 'Install packages!'
    workingDir "${projectDir}"
    ignoreExitValue = true
    if (System.getProperty("os.name").toLowerCase().contains("windows")) {
        commandLine("cmd", "/c", "npm", "install")
    } else {
        commandLine("npm", "install")
    }
}

task npmBuild(type:Exec) {
    description 'Build the App!'
    workingDir "${projectDir}"
    ignoreExitValue = true
    if (System.getProperty("os.name").toLowerCase().contains("windows")) {
        commandLine("cmd", "/c", "npm", "run", "build")
    } else {
        commandLine("npm", "run", "build")
    }
}

//task perepareDockerfile(type: Copy) {
//    from (docker)
//}


build {
    finalizedBy npmInstall
    finalizedBy npmBuild
}