buildscript {
    ext {
        devopsDistrPackage = "ru.fk.ekb2.ui-cabinet-v3"
        devopsArtifactId = "ekb2-ui-cabinet"
        devopsArtifactVersion = "3.0"
    }
    repositories {
        mavenCentral()
    }
    dependencies {
    }
}

apply plugin:'base'


task yarnInstall(type:Exec) {
    description 'Install packages!'
    workingDir "${projectDir}"
    ignoreExitValue = true
    if (System.getProperty("os.name").toLowerCase().contains("windows")) {
        commandLine("cmd", "/c", "yarn", "install")
    } else {
        commandLine("yarn", "install")
    }
}

task npmBuild(type:Exec) {
    description 'Build the App!'
    workingDir "${projectDir}"
    ignoreExitValue = true
    if (System.getProperty("os.name").toLowerCase().contains("windows")) {
        commandLine("cmd", "/c", "npm", "run", "build")
    } else {
        commandLine("npm", "run", "build")
    }
}

//task perepareDockerfile(type: Copy) {
//    from (docker)
//}


build {
    finalizedBy yarnInstall
    finalizedBy npmBuild
}